[package]
name = "talloc"
version = "1.0.1"
edition = "2021"
readme = "README.md"
authors = ["Shaun Beautement"]
description = "A fast, consistant, and flexible `no_std`-compatible allocator."
repository = "https://github.com/SFBdragon/talloc"
keywords = ["allocator", "no_std", "kernel", "memory", "heap"]
categories = ["memory-management", "no-std", "embedded"]
license = "MIT"
exclude = [
    "benchmark_graphs",
    "benchmark_results",
]


[features]
allocator = ["spin"]
default = ["spin", "allocator"]


[dependencies]
spin = { version = "0.9.4", optional = true }

[dev-dependencies]
simple-chunk-allocator = "0.1.5"
linked_list_allocator = { version = "0.10.3", features =  ["use_spin_nightly", "const_mut_refs", "alloc_ref"] }
good_memory_allocator = { version = "0.1.7", features = ["spin", "allocator"] }
average = "0.13.1"
fastrand = "1.9.0"
tikv-jemallocator = { version = "0.5.0", features = [] }


[profile.release]
lto = true
codegen-units = 1
panic = "abort"
