[package]
name = "talloc"
version = "0.1.0"
edition = "2021"
authors = ["Shaun Beautement"]
description = "An extremely performant, flexible, and `no_std`-compatible allocator."
repository = "TODO"
keywords = ["allocator", "no_std", "kernel", "memory", "heap"]
categories = ["memory-management", "no-std", "embedded"]
license = "MIT"


[dependencies]
spin = { version = "0.9.4", optional = true }

[features]
default = ["spin", "allocator"]
allocator = ["spin"]

[dev-dependencies]
rand = "0.8.5"
simple-chunk-allocator = "0.1.5"
linked_list_allocator = { version = "0.10.3", features =  ["use_spin_nightly", "const_mut_refs", "alloc_ref"] }
good_memory_allocator = { version = "0.1.7", features = ["spin", "allocator"] }
average = "0.13.1"
fastrand = "1.9.0"


[profile.release]
lto = true
codegen-units = 1
panic = "abort"
