[package]
name = "talc"
version = "4.2.0"
rust-version = "1.67.1"
edition = "2021"
readme = "README.md"
authors = ["Shaun Beautement"]
description = "A fast and flexible allocator for no_std and WebAssembly"
repository = "https://github.com/SFBdragon/talc"
keywords = ["allocator", "no_std", "memory", "heap", "wasm"]
categories = ["memory-management", "no-std", "embedded", "wasm"]
license = "MIT"
exclude = [
    "benchmark_graphs",
    "benchmark_results",
    "wasm-size",
    "wasm-size.sh",
    "wasm-perf",
    "wasm-perf.sh",
]


[features]
fuzzing = []
counters = []
nightly_api = []
allocator = ["lock_api"]
default = ["lock_api", "allocator", "nightly_api"]


[dependencies]
lock_api = { version = "0.4", optional = true, default-features = false }

[dev-dependencies]
fastrand = "1.9"
spin = { version = "0.9.8", default-features = false, features = ["lock_api", "spin_mutex"] }
linked_list_allocator = { version = "0.10", features =  ["use_spin_nightly", "const_mut_refs", "alloc_ref"] }
good_memory_allocator = { version = "0.1", features = ["spin", "allocator"] }
buddy-alloc = "0.5"
dlmalloc = { version =  "0.2.4", default-features = false, features = ["global"] }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
