[package]
name = "talc-wasm-example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies.talc]
path = ".."
default-features = false
features = ["lock_api"]

[profile.release]
opt-level = "s"
lto = "fat"
