[package]
name = "fuzzing"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
arbitrary = { version = "1", features = ["derive"] }
spin = "0.9.8"
rand = "0.8.5"

[dependencies.talc]
path = "../talc"
features = ["fuzzing", "counters"]

[[bin]]
name = "fuzz_talc"
path = "fuzz_targets/fuzz_talc.rs"
test = false
doc = false
