[package]
name = "wasm-size"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
lol_alloc = { version = "0.4.0", optional = true }
dlmalloc = { version = "0.2.4", optional = true }
lock_api = "0.4.10"

[dependencies.talc]
path = ".."
default-features = false
features = ["lock_api"]

[features]
default = []

[profile.release]
opt-level = "z"
lto = "fat"
