[book]
authors = ["Shaun Beautement"]
language = "en"
multilingual = false
src = "src"
title = "Talc Documentation"

[rust]
edition = "2021"

[output.html]
git-repository-url = "https://github.com/SFBdragon/talc/tree/main/book"
edit-url-template  = "https://github.com/SFBdragon/talc/tree/main/book/{path}"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2